### ISSUE TITLE
Contribute to the TLA+ examples

### ISSUE THREAD

**Issue by lemmy** [mryndzionek/tlaplus_specs#1]
Hi,

would you be interested in contributing your specs to the [TLA+ examples](https://github.com/tlaplus/Examples/)?  Most examples are licensed under [MIT](https://github.com/tlaplus/Examples/blob/master/LICENSE.md).

Thanks

**Comment by mryndzionek** [comment]
Hi,
Yes, sure! Do you need my help with moving them to [tlaplus/Examples](https://github.com/tlaplus/Examples/)? Is there a way to easily sync the specs in two repos? What about the images/graphs? Can/should they also be moved?

**Comment by lemmy** [comment]
Good point, the images and graphs would probably blow the TLA+ example repository out of proportion and they might be of limited use to TLA+ adopters.

**Comment by mryndzionek** [comment]
Maybe just copy the .tla files with a link back to this repo.

**Comment by lemmy** [comment]
Can you create a PR with the .tla files and a README?

**Comment by mryndzionek** [comment]
I'll probably have time to do it on the weekend.

**Comment by mryndzionek** [comment]
Okay, I made a PR with 3 specs: https://github.com/tlaplus/Examples/pull/16
Not sure if it's worth to add the other ones.
